# Divisions
MIDDLE_SCHOOL = "Middle School"
MS = MIDDLE_SCHOOL
HIGH_SCHOOL = "High School"
HS = HIGH_SCHOOL
OPEN = "Open"
ALL_SERVICE = "All Service"
AS = ALL_SERVICE

# Sorts
TEAM_NUMBER = "Number"
NUMBER = TEAM_NUMBER
LOCATION_CATEGORY = "Location"
LOCATION = LOCATION_CATEGORY
CATEGORY = LOCATION_CATEGORY
SCORED_IMAGES = "Images"
IMAGES = SCORED_IMAGES
PLAY_TIME = "Received"
TIME = PLAY_TIME
WARNING = "Warning"
WARN = WARNING
CCS_SCORE = "Score"
SCORE = CCS_SCORE